FROM python:3

WORKDIR /usr/src/app

RUN pip install --upgrade pip==20.0.2
COPY requirements.txt ./
COPY src ./src
RUN pip install --no-cache-dir -r requirements.txt \
    && pip install -e /usr/src/app/src

EXPOSE 8082

CMD [ "python -m settlingInSpace.game.main" ]