FROM python:3

WORKDIR /app

RUN pip install --upgrade pip==20.0.2
COPY dash/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY dash .

EXPOSE 8050

ENTRYPOINT ["python"]

CMD ["src/app.py"]