FROM python:3

WORKDIR /app

RUN pip install --upgrade pip==21.1.1
COPY admin/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY admin/admin_dash/admin_app.py /app/admin_app.py

EXPOSE 8050

ENTRYPOINT ["python"]

CMD ["/app/admin_app.py"]