FROM python:3

WORKDIR /app

RUN pip install --upgrade pip==20.0.2
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY admin/rpc_server/admin_rpc.py .

EXPOSE 8082
EXPOSE 8088

CMD ["python", "/app/admin_rpc.py"]