= Settling in Space

== Installation

You need to install docker, docker-compose.

To start game navigate into the repo directory and run

docker-compose up

In development

docker-compose up --build

Open a browser and play:

localhost:8082 <- Jupyterlab

localhost:8083 <- Admin Site

localhost:8081 <- Game Site

== short description
It is a game about expanding earths hegemony in a part of our galaxy.

This game is splittet in two parts:

* expanding earth hegemony
* war against unknown invading species and if you win this war the founding of the federation of planets

== description
You are commander-in-chief of early earth Starfleet. Your aim is it to protect the earth. Doing so you have to manage economy for building and maintaining starships, to send them out to explore, colonize new worlds and to form alliances with other species.

Your challange is it to command your ships to their missions and building infrastructure in outerspace when communitcation needs time between earth and your ships and colonies.


https://testdriven.io/blog/developing-a-single-page-app-with-flask-and-vuejs/#flask-setup